language: php
php:
  - 5.3

branches:
  only:
    - master

before_script:
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer install --dev --prefer-dist

script: phpunit

notifications:
  irc: "irc.freenode.org#webforge"
  mail: p.scheit@ps-webforge.com